### ISSUE TITLE
Install of 15.0.4snap1 fails (mysql setup problem)

### ISSUE THREAD

**Issue by mikesi** [nextcloud/nextcloud-snap#913]
Running as root:
nextcloud.manual-install adminuser somepassword
the command hangs on:
Waiting for PHP...

Checking the system logs:
Feb 23 19:10:57 nextcloud nextcloud.php-fpm[12802]: Waiting for MySQL...
Feb 23 19:10:57 nextcloud nextcloud.mysql[12779]: Starting MySQL
Feb 23 19:10:57 nextcloud nextcloud.apache[12849]: Waiting for PHP...
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: No renewals were attempted.
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: No hooks were run.
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 23 19:11:02 nextcloud mysqld_safe[14025]: Starting mysqld daemon with databases from /var/snap/nextcloud/11688/mysql
Feb 23 19:11:02 nextcloud mysqld[14027]: /snap/nextcloud/11688/bin/mysqld (mysqld 5.7.22-log) starting as process 14027 ...
Feb 23 19:11:02 nextcloud mysqld[14027]: failed to set datadir to /var/snap/nextcloud/11688/mysql/
Feb 23 19:11:02 nextcloud mysqld[14027]: Aborting
Feb 23 19:11:02 nextcloud mysqld[14027]: Binlog end
Feb 23 19:11:02 nextcloud mysqld[14027]: /snap/nextcloud/11688/bin/mysqld: Shutdown complete
Feb 23 19:11:02 nextcloud mysqld_safe[14033]: mysqld from pid file /tmp/pids/mysql.pid ended
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: ...... * The server quit without updating PID file (/tmp/pids/mysql.pid).
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: sed: can't read /var/snap/nextcloud/11688/mysql/root.ini: No such file or directory
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: Waiting for MySQL...

Seems that mysql setup fails (can't set owner of data directory) and the install process just hangs and waits.

OS:
Ubuntu 18.04.2 LTS

Snap info:
installed: 15.0.4snap1 (11688) 196MB -

**Comment by BernieO** [comment]
Even as root you need to run this command with sudo.
Can you try again with a prefixed sudo?
Ref: 
https://github.com/nextcloud/server/issues/14359#issuecomment-466746435

**Comment by mikesi** [comment]
Hi @BernieO 
Running with sudo produces the same result.
One note it's in a LXD container.

Feb 24 09:22:01 nextcloud nextcloud.nextcloud-fixer[79039]: Waiting for Apache...
Feb 24 09:22:03 nextcloud nextcloud.apache[78985]: Making sure nextcloud is setup...
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.702197Z 0 [Warning] The syntax '--log_warnings/-W' is deprecated and will be removed in a future release. Please use '--log_error_verbosity' instead.
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.708108Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.717772Z 0 [Note] Ignoring --secure-file-priv value as server is running with --initialize(-insecure) or --bootstrap.
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.727624Z 0 [Note] mysqld (mysqld 5.7.22-log) starting as process 79216 ...
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.844621Z 0 [Note] Creating the data directory /var/snap/nextcloud/11688/mysql/
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.994866Z 0 [ERROR] Can't change data directory owner to mysql
Feb 24 09:22:03 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:03.995150Z 0 [ERROR] Aborting
Feb 24 09:22:04 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:04.011140Z 0 [Note] Binlog end
Feb 24 09:22:04 nextcloud nextcloud.mysql[78999]: 2019-02-24T09:22:04.037854Z 0 [Note] mysqld: Shutdown complete
Feb 24 09:22:05 nextcloud nextcloud.php-fpm[79016]: Waiting for MySQL...
Feb 24 09:22:05 nextcloud nextcloud.mysql[78999]: Starting MySQL
Feb 24 09:22:06 nextcloud nextcloud.apache[78985]: Waiting for PHP...
Feb 24 09:22:07 nextcloud nextcloud.renew-certs[79023]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Feb 24 09:22:07 nextcloud nextcloud.renew-certs[79023]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 24 09:22:07 nextcloud nextcloud.renew-certs[79023]: No renewals were attempted.
Feb 24 09:22:07 nextcloud nextcloud.renew-certs[79023]: No hooks were run.
Feb 24 09:22:07 nextcloud nextcloud.renew-certs[79023]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 24 09:22:11 nextcloud mysqld_safe[80194]: Starting mysqld daemon with databases from /var/snap/nextcloud/11688/mysql
Feb 24 09:22:11 nextcloud mysqld[80196]: /snap/nextcloud/11688/bin/mysqld (mysqld 5.7.22-log) starting as process 80196 ...
Feb 24 09:22:11 nextcloud mysqld[80196]: failed to set datadir to /var/snap/nextcloud/11688/mysql/
Feb 24 09:22:11 nextcloud mysqld[80196]: Aborting
Feb 24 09:22:11 nextcloud mysqld[80196]: Binlog end
Feb 24 09:22:11 nextcloud mysqld[80196]: /snap/nextcloud/11688/bin/mysqld: Shutdown complete
Feb 24 09:22:11 nextcloud mysqld_safe[80204]: mysqld from pid file /tmp/pids/mysql.pid ended
Feb 24 09:22:12 nextcloud nextcloud.mysql[78999]: ...... * The server quit without updating PID file (/tmp/pids/mysql.pid).
Feb 24 09:22:12 nextcloud nextcloud.mysql[78999]: sed: can't read /var/snap/nextcloud/11688/mysql/root.ini: No such file or directory
Feb 24 09:22:12 nextcloud nextcloud.mysql[78999]: Waiting for MySQL...

**Comment by m-nogues** [comment]
I am having the same problem on debian 9.

The installation just hangs on the "Waiting for PHP..." message.

**Comment by cestpasphoto** [comment]
Same problem here with Nextcloud 15.0.5snap1 on Debian.
If you check #819 #745 #733, it seems that snap uses system mysql instead of the snap version. Deleting system mysql solves the issue, but it is not possible in my case.

**Comment by kyrofa** [comment]
Yeah there seems to be a snapd bug causing the snap to run mysql from the host instead of out of the snap. I've logged that bug [here](https://bugs.launchpad.net/snapd/+bug/1819734).

**Comment by sbelardi-gpfw** [comment]
Thanks @kyrofa . Do you need additional details like snapd version?

**Comment by cestpasphoto** [comment]
Thanks @kyrofa : do you need additional details like snapd version?

**Comment by zyga** [comment]
Hello. I'll have a look. Is it fair to say that Debian 9 is sufficient to reproduce the issue?

**Comment by cestpasphoto** [comment]
I personally am on Debian Sid

**Comment by patman-cp** [comment]
Any known workarounds for this?

I hit this running Fedora 29.

It looks like this has been a problem since Jan 2018.

I don't see any fixes in snapd, per https://bugs.launchpad.net/snapd/+bug/1819734

**Comment by mhdion** [comment]
$lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

I can confirm that after removing, and purging, every *myslq* and *mariadb* packages I was able to install and configure nextcloud using snap.

**Comment by cestpasphoto** [comment]
Did you remove _mysql_ and _mariadb_ packages on the host, or on the snap? The goal is that snap packages should work, whatever the packages are installed on host side.

**Comment by mhdion** [comment]
I removed, and purged, old mysql packages and latest mariadb packages.

After that, I re-installed the nextcloud snap and it worked as expected.

By the way, I also removed apache2 in order to free the 80 and 443 TCP 
ports. After getting nextcloud up and running, I installed apache2 again 
and changed it ports.

Now, It's working fine.

I have not make the test of installing again mariadb and to check if it 
interferes with nextcloud's snap

**Comment by xkl** [comment]
folks, a dirty workaround that works for me (running bullseye):

    $ mv /etc/mysql /etc/mysql.tmp
    $ snap restart nextcloud
    $ mv /etc/mysql.tmp /etc/mysql

-xkl

**Comment by kyrofa** [comment]
> folks, a dirty workaround that works for me (running bullseye):

Note that you will need to do that every time the snap updates or the machine restarts.

**Comment by xkl** [comment]
> > folks, a dirty workaround that works for me (running bullseye):
> 
> Note that you will need to do that every time the snap updates or the machine restarts.

just dont ask, how I handle this, it's not getting cleaner....

**Comment by kyrofa** [comment]
> just dont ask, how I handle this, it's not getting cleaner....

Hahaha :see_no_evil:

**Comment by kyrofa** [comment]
@zyga any progress on this?

**Comment by zyga** [comment]
@kyrofa I noticed this but I don't know what the problem is really.

- nextcloud is not using classic confinement, that's good
- mysql inside the snap and on the host are sharing all IPC primitives so perhaps one is substituted for the other for connection requests
- host's /etc is visible for snaps so perhaps the presence of mysql config file causes issues for the next cloud snap

Perhaps the expectations are wrong? Could we have a chat about this when you are online?

**Comment by maxbritto** [comment]
I can confirm that removing mysql and mariadb from the host worked for me : 
`sudo apt remove mariadb`
`sudo apt remove mysql`
`sudo apt autoremove`
`sudo apt purge`

Then run the snap install of nextcloud and it should work.
I'm on a fresh raspbian lite

**Comment by kyrofa** [comment]
> - host's /etc is visible for snaps so perhaps the presence of mysql config file causes issues for the next cloud snap

@zyga that doesn't seem true on Ubuntu, at least not entirely. I can cat `/etc/hosts`, for example, but:

```
$ sudo snap run --shell nextcloud.mysql <<EOF
cat /etc/mysql/my.cnf
EOF
cat: /etc/mysql/my.cnf: Permission denied
```

That's accompanied by the following in the syslog:

```
Oct 22 16:25:45 protege kernel: [339197.020803] audit: type=1400 audit(1571786745.884:1806): apparmor="DENIED" operation="open" profile="snap.nextcloud.mysql" name="/etc/mysql/my.cnf.fallback" pid=12091 comm="cat" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

```

**Comment by zyga** [comment]
@kyrofa permissions are another layer. My point is that `/etc` is _there_ and it's the host's `/etc/`, yes it is bind-mounted.

On Debian confinement is not enabled and you will actually successfully read the host's `/etc/mysql/*` files.

**Comment by kyrofa** [comment]
That's almost certainly the issue, then. It seems MySQL parses all the configuration files it can find, starting with `/etc`. On Debian, snaps are not properly isolated and it ends up reading the configuration from the host. I will look into ways to disable that behavior, but I will admit that playing cross-distro whack-a-mole is not my highest priority. If anyone has any ideas please propose them.

**Comment by zyga** [comment]
@kyrofa do a layout of `tmpfs` over /etc

**Comment by efrasyad** [comment]
Same issue when upgrading from 15 to 16, solved using @xkl workaround.
Will there be permanent fix for future upgrade?

Thanks.

**Comment by rbwrightjr91** [comment]
> I can confirm that removing mysql and mariadb from the host worked for me :
> `sudo apt remove mariadb`
> `sudo apt remove mysql`
> `sudo apt autoremove`
> `sudo apt purge`
> 
> Then run the snap install of nextcloud and it should work.
> I'm on a fresh raspbian lite

This worked for me, Ubuntu 18.04 LTS

**Comment by gerhartob** [comment]
> folks, a dirty workaround that works for me (running bullseye):
> 
> ```
> $ mv /etc/mysql /etc/mysql.tmp
> $ snap restart nextcloud
> $ mv /etc/mysql.tmp /etc/mysql
> ```
> 
> -xkl
I don't know if this is better or even more ugly, but at least it's automated...
I've created an systemd overlay unit file and a script for the snap.nextcloud.mysql.service.
This way the SQL instance of the snap is started after the host SQL damon and the host config is moved into a temp dir before starting it and after starting it the config is restored.

`systemctl edit snap.nextcloud.mysql.service`
add the following lines:
`[Unit]
After=mysqld.service
[Service]
ExecStartPre=+/usr/local/bin/nextcloud-snap-mysql-fix enable 2
ExecStartPost=+/usr/local/bin/nextcloud-snap-mysql-fix undo 10`

and put this script into /usr/local/bin/nextcloud-snap-mysql-fix:
[snap-nextcloud-mysql-fix.txt](https://github.com/nextcloud/nextcloud-snap/files/4160472/snap-nextcloud-mysql-fix.txt)

**Comment by patman-cp** [comment]
I'm no longer hitting this on Fedora 31. I haven't tried in a while and don't know how this was fixed.

I Fedora 31 up to date, though I'm using a recent git kernel to test some other problems on my system but that should not change anything:

# snap --version
snap    2.43.3-1.fc31
snapd   2.43.3-1.fc31
series  16
fedora  31
kernel  5.7.0-rc2+

# snap list nextcloud
Name       Version      Rev    Tracking  Publisher   Notes
nextcloud  18.0.4snap1  20498  stable    nextcloud✓  -

**Comment by xkl** [comment]
**status report**, unfortunately not solved on the following setup, and still using the dirty workaround:

```
# . /etc/os-release; echo $PRETTY_NAME
Debian GNU/Linux 10 (buster)

# snap --version
snap    2.45
snapd   2.45
series  16
debian  10
kernel  4.19.0-9-amd64

# snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.0snap1  21796  latest/stable  nextcloud✓  -

```

**Comment by Dinsmoor** [comment]
Hey this is still a problem on Debian, installing mysql-common will kill the nextcloud snap. This issue has been open for a long time. What can we do to help?

**Comment by kyrofa** [comment]
Someone encountering this error, can you please provide the output of the following command?

    $ snap run --shell nextcloud.mysql -c 'mysqld --print-defaults'

**Comment by kyrofa** [comment]
Also, if you have this problem, try the `beta/issue-913` channel and let me know if it fixes it:

    $ sudo snap install nextcloud --channel=latest/beta/issue-913

Or if you already have it installed:

    $ sudo snap refresh nextcloud --channel=latest/beta/issue-913

**Comment by xkl** [comment]
Here you are!

<pre>
# snap run --shell nextcloud.mysql -c 'mysqld --print-defaults'
mysqld would have been started with the following arguments:
--user=mysql --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock
--port=3306 --basedir=/usr --datadir=/var/lib/mysql --tmpdir=/tmp --lc-messages-dir=/usr/share/mysql
--skip-external-locking --bind-address=127.0.0.1 --key_buffer_size=16M --max_allowed_packet=16M
--thread_stack=192K --thread_cache_size=8 --myisam_recover_options=BACKUP --query_cache_limit=1M
--query_cache_size=16M --log_error=/var/log/mysql/error.log --expire_logs_days=10
--max_binlog_size=100M --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci 
</pre>

and

<pre>
# snap run --shell nextcloud.mysql -c 'mysqld --defaults-file=$SNAP/my.cnf --print-defaults'
mysqld would have been started with the following arguments:
--user=root --max_allowed_packet=100M --secure-file-priv=NULL --skip-networking
</pre>

I will try the `beta/issue-913` channel later today or tomorrow evening (CEST), and report the results.

Thanks for revisiting this issue.

-xkl

**Comment by DrOwl** [comment]
For me:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```


```
# snap run --shell nextcloud.mysql -c 'mysqld --print-defaults'
mysqld would have been started with the following arguments:
--user=mysql --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306 --basedir=/usr --datadir=/var/lib/mysql --tmpdir=/tmp --lc-messages-dir=/usr/share/mysql --skip-external-locking --bind-address=127.0.0.1 --key_buffer_size=16M --max_allowed_packet=16M --thread_stack=192K --thread_cache_size=8 --myisam-reco

```
```

# snap run --shell nextcloud.mysql -c 'mysqld --defaults-file=$SNAP/my.cnf --print-defaults'
mysqld would have been started with the following arguments:
--user=root --max_allowed_packet=100M --secure-file-priv=NULL --skip-networking 

```

I have tried the beta as follows:

```

#  snap remove nextcloud                                                                                                               
nextcloud removed

#  snap saved
Set  Snap       Age    Version      Rev    Size    Notes
6    nextcloud  9.96s  19.0.1snap1  22327   2468B  auto

# snap forget 6
Snapshot #6 forgotten.

# snap install nextcloud --channel=latest/beta/issue-913
nextcloud (beta/issue-913) 19.0.1snap1+git1.f4c9f02 from Nextcloud✓ installed

```

```

# snap start nextcloud
Started.

# snap logs -f  nextcloud                                                                                                              
2020-07-22T11:07:21Z nextcloud.mysql[32451]: 2020-07-22T11:07:21.675196Z 0 [ERROR] Aborting
2020-07-22T11:07:21Z nextcloud.mysql[32451]: Starting MySQL
2020-07-22T11:07:23Z nextcloud.renew-certs[32488]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
2020-07-22T11:07:23Z nextcloud.renew-certs[32488]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2020-07-22T11:07:23Z nextcloud.renew-certs[32488]: No renewals were attempted.
2020-07-22T11:07:23Z nextcloud.renew-certs[32488]: No hooks were run.
2020-07-22T11:07:23Z nextcloud.renew-certs[32488]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2020-07-22T11:07:27Z nextcloud.mysql[32451]: ...... * The server quit without updating PID file (/tmp/pids/mysql.pid).
2020-07-22T11:07:27Z nextcloud.mysql[32451]: sed: can't read /var/snap/nextcloud/22369/mysql/root.ini: No such file or directory
2020-07-22T11:07:27Z nextcloud.mysql[32451]: Waiting for MySQL...

```



```

#  snap run --shell nextcloud.mysql -c 'mysqld --print-defaults'
mysqld would have been started with the following arguments:
--user=mysql --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306 --basedir=/usr --datadir=/var/lib/mysql --tmpdir=/tmp --lc-messages-dir=/usr/share/mysql --skip-external-locking --bind-address=127.0.0.1 --key_buffer_size=16M --max_allowed_packet=16M --thread_stack=192K --thread_cache_size=8 --myisam-recover=BACKUP --query_cache_limit=1M --query_cache_size=16M --log_error=/var/log/mysql/error.log --expire_logs_days=10 --max_binlog_size=100M 


# snap run --shell nextcloud.mysql -c 'mysqld --defaults-file=$SNAP/my.cnf --print-defaults'
mysqld would have been started with the following arguments:
--user=root --max_allowed_packet=100M --secure-file-priv=NULL --skip-networking 

```

**Comment by kyrofa** [comment]
Ah, missed one, but okay now I'm pretty confident in this. See #1414, and test it out using the `latest/beta/pr-1414` branch.

**Comment by Dinsmoor** [comment]
@kyrofa 
The latest/beta/pr-1414 branch works for me.
I can have both mariadb-server (mysql) running and also have the nextcloud snap working correctly.
It does seem slower? May be just my perception, but at least this giant bug has a fix.
Thank you very much, now I can actually store my kids' photos and run other applications.
-Fellow Dad

**Comment by kyrofa** [comment]
> The latest/beta/pr-1414 branch works for me.

Excellent, I'll ship it then, thank you.

> It does seem slower? May be just my perception, but at least this giant bug has a fix.

Slower than not working at all :stuck_out_tongue: ? Or slower than when you didn't have mariadb-server installed, and thus could use the snap? If the latter, I can't explain it other than perception, because it should have ended up doing the same thing as it's doing now. In fact, I would expect it to start up a smidge faster since it's not looking for other files at all anymore.

**Comment by rozatoo** [comment]
Snap installing Nextcloud on a AWS Lightsail instance with Ubuntu 20.04 LTS this issue still appears

**Comment by g3r4** [comment]
@rozatoo This happened to me recently on a AWS Lightsail with Ubuntu 20.04 using the smallest ($3.50/mo) instance: 
Memory 512MB
Processing 1vCPU
Storage 20GB SSD
Transfer 1TB

I was getting the `"Waiting for PHP..."` message/error whenever I tried running `sudo nextcloud.manual-install <admin> <password>`

I spent some time debugging it and it looks like snap cannot install or start Nextcloud services with that small amount of memory, even though the [minimum amount of memory required to run Nextcloud is 128MB and  the recommended is 256MB RAM](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#memory). Since we are running it with snap, the memory size needs to be larger. Actually, if you try to run the [official script to install Nextcloud and its dependencies on production ](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh) (this method does not use snap), the script won't let you , [it checks for at least 2GB of RAM](https://github.com/nextcloud/vm/blob/e6d9133db785ca8fed14a952fbe7fb31b25cc831/nextcloud_install_production.sh#L128):

```
# Test RAM size (2GB min) + CPUs (min 1)
ram_check 2 Nextcloud
cpu_check 1 Nextcloud
```

I was successful at installing Nextcloud with snap on the next AWS Lightsail size instance with Ubuntu 20.04 ($5.00/mo):
Memory 1 GB
Processing 1vCPU
Storage 40GB SSD
Transfer 2TB

However, after running the instance for a bit and checking both `htop` and the actual system monitoring within my instance, this is what I found:

![Screenshot 2021-08-15 at 22-51-36 Settings - Nextcloud](https://user-images.githubusercontent.com/8062569/129505291-59465e03-c406-4564-9a7a-f46f3407a2de.png)

Even the second tier of AWS Lightsail is already close to its memory limit! If you want to have a reliable Nextcloud instance, you will need to get the next tier ($10.00/mo) to have at least 2GB of RAM.

Hope this helps!

**Comment by rozatoo** [comment]
Thanks for the reply! 

I ended up testing the the 5 dollar 1GB ram instance and found that then I was able to snap install nextcloud. But due to nextcloud using around 900MB ram while idle I upgraded to the 2GB ram instance :)

So in the end I came to the same conclusion.

Hope your reply helps someone out who googles this issue in the future ;)

Thank you!

**Comment by keybutton** [comment]
Hi,

I am working on a fresh local installation of Ubuntu 22.04 LTS Desktop. The same issue occurs again. I have neither installed mysql nor mariadb.

The stdout from the command "snap logs nextcloud" shows the following:
2022-06-04T19:56:25+02:00 systemd[1]: Started Service for snap application nextcloud.mysql.
2022-06-04T19:56:34+02:00 nextcloud.mysql[163297]: Starting MySQL
2022-06-04T19:56:35+02:00 nextcloud.mysql[163297]: . * The server quit without updating PID file (/tmp/pids/mysql.pid).
2022-06-04T19:56:35+02:00 systemd[1]: snap.nextcloud.mysql.service: Main process exited, code=exited, status=1/FAILURE
2022-06-04T19:56:35+02:00 systemd[1]: snap.nextcloud.mysql.service: Failed with result 'exit-code'.
2022-06-04T19:56:35+02:00 systemd[1]: snap.nextcloud.mysql.service: Consumed 5.169s CPU time.
2022-06-04T19:56:35+02:00 systemd[1]: snap.nextcloud.mysql.service: Scheduled restart job, restart counter is at 2.
2022-06-04T19:56:35+02:00 systemd[1]: Stopped Service for snap application nextcloud.mysql.
2022-06-04T19:56:35+02:00 systemd[1]: snap.nextcloud.mysql.service: Consumed 5.169s CPU time.
2022-06-04T19:56:35+02:00 systemd[1]: Started Service for snap application nextcloud.mysql.


When trying out nextcloud on an Ubuntu-Startup-USB-Stick it works fine, but when I install  Ubuntu via the USB-Stick it does not work any more. So this might give you a hint of the cause of the problem.
